---
name: Automation for Docker Kubectl
on:
  workflow_dispatch:
  push:
    paths:
      - "Makefile"
    branches:
      - main
env:
  GITHUB_TOKEN: ${{secrets.ORG_GITHUB_TOKEN}}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
      - name: docker login
        run: make login
      - name: docker build
        run: make build
      - name: docker push
        run: make push
